version: '3'

services:
  db:
    image: postgres
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    env_file: .env
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: /src/entrypoint.sh

volumes:
  postgres_data: